-- Run once in Supabase Dashboard > SQL Editor.
-- Secure default: RLS is enabled and no public policies are created.
-- Use SUPABASE_SECRET_KEY in the server-side Streamlit Secrets for this admin app.

create table if not exists public.app_metadata (
    key text primary key,
    value text not null
);

create table if not exists public.taxonomy_features (
    taxonomy_id text primary key,
    business_family text not null,
    business_submodule text not null,
    business_detail text not null,
    sort_order integer not null,
    is_active boolean not null default true,
    source text not null default 'taxonomy_pipeline',
    created_at timestamptz not null,
    updated_at timestamptz not null,
    unique (business_family, business_submodule, business_detail)
);

create table if not exists public.named_clusters (
    platform text not null check (platform in ('android', 'ios')),
    cluster_id integer not null,
    taxonomy_id text references public.taxonomy_features(taxonomy_id)
        on update cascade on delete set null,
    cluster_name text not null,
    business_family text not null,
    business_submodule text not null,
    business_detail text not null default '',
    naming_confidence text not null,
    naming_source text not null,
    needs_review boolean not null,
    score_share double precision,
    evidence_mass_coverage double precision,
    evidence_row_coverage double precision,
    supporting_evidence text not null default '',
    top_ngrams text not null default '',
    size bigint not null default 0,
    share double precision not null default 0,
    row_count_in_input bigint not null default 0,
    updated_at timestamptz not null,
    primary key (platform, cluster_id)
);

create table if not exists public.change_audit (
    audit_id bigint generated by default as identity primary key,
    entity_type text not null,
    entity_key text not null,
    old_value jsonb not null default '{}'::jsonb,
    new_value jsonb not null default '{}'::jsonb,
    changed_at timestamptz not null
);

create index if not exists idx_taxonomy_active_path
    on public.taxonomy_features(is_active, business_family, business_submodule, business_detail);
create index if not exists idx_clusters_review
    on public.named_clusters(platform, needs_review, naming_confidence);
create index if not exists idx_clusters_taxonomy
    on public.named_clusters(taxonomy_id);
create index if not exists idx_audit_entity
    on public.change_audit(entity_type, entity_key, changed_at desc);

alter table public.app_metadata enable row level security;
alter table public.taxonomy_features enable row level security;
alter table public.named_clusters enable row level security;
alter table public.change_audit enable row level security;

grant all on table public.app_metadata to service_role;
grant all on table public.taxonomy_features to service_role;
grant all on table public.named_clusters to service_role;
grant all on table public.change_audit to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Do not add anonymous write policies for this business-review tool.
-- If Supabase Auth is added later, create narrowly scoped policies for authenticated users.
