#!/usr/bin/env python3
"""Create an interactive customer -> session -> journey path HTML.

This replaces the hard-coded token sample in the original reference script. The input
is ``journey_path_detail.csv`` generated by
``scripts/build_customer_journey_sequences.py``. The HTML contains four controls:

* customer_id
* session_id (scoped to the selected customer and platform)
* path level: business family, business submodule, cluster, or stable family code
* focus value: aggregate the immediately previous and next journeys for that value

The first chart is a timestamp-ordered journey path. Without a focus value, the second
chart is a Sankey of the selected session. With a focus value, it searches all loaded
detail sessions and shows the immediate previous -> focus -> next journeys, together with
a statistics table. The source export has timestamps at journey level only, so token
strings are shown in the table/hover text but are not given invented event timestamps.

Example:
    python visualize/pm4py_visualize.py \
      --input output/scores/pca48_ngrams12_500/customer_journey_sequences/journey_path_detail.csv \
      --output output/scores/pca48_ngrams12_500/customer_journey_sequences/journey_paths.html
"""

from __future__ import annotations

import argparse
import csv
import html
import json
from collections import Counter
from pathlib import Path


LEVEL_COLUMNS = {
    "business_family": "business_family",
    "business_submodule": "business_submodule",
    "business_detail": "business_detail",
    "cluster": "cluster_name",
    "business_family_code": "business_family_code",
}
REQUIRED_COLUMNS = {"customer_id", "platform", "session_id", "session_journey_index", "journey_id"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True, help="journey_path_detail.csv")
    parser.add_argument("--output", type=Path, required=True, help="HTML path to write")
    parser.add_argument(
        "--level",
        choices=tuple(LEVEL_COLUMNS),
        default="business_submodule",
        help="initial path label level; the HTML can switch levels afterwards",
    )
    parser.add_argument("--top-customers", type=int, default=0, help="optional display cap; 0 = all input customers")
    parser.add_argument("--top-sessions", type=int, default=0, help="optional display cap; 0 = all input sessions")
    parser.add_argument("--title", default="Customer journey sequence")
    return parser.parse_args()


def clean(value: object, fallback: str = "__unknown__") -> str:
    text = "" if value is None else str(value).strip()
    return text or fallback


def read_detail(path: Path, top_customers: int, top_sessions: int) -> list[dict[str, str]]:
    if not path.exists():
        raise SystemExit(f"input not found: {path}")
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        columns = set(reader.fieldnames or [])
        missing = REQUIRED_COLUMNS - columns
        if missing:
            raise SystemExit(
                f"{path} is not journey_path_detail.csv; missing {', '.join(sorted(missing))}. "
                "Run scripts/build_customer_journey_sequences.py first."
            )
        rows = []
        for raw in reader:
            row = {key: clean(raw.get(key), "") for key in columns}
            row["customer_id"] = clean(raw.get("customer_id"), "__anonymous__")
            row["platform"] = clean(raw.get("platform"), "unknown")
            row["session_id"] = clean(raw.get("session_id"), "__unknown_session__")
            row["session_journey_index"] = clean(raw.get("session_journey_index"), "0")
            row["journey_id"] = clean(raw.get("journey_id"), "__unknown_journey__")
            rows.append(row)

    if top_customers < 0 or top_sessions < 0:
        raise SystemExit("--top-customers and --top-sessions must be >= 0")
    if top_customers:
        counts = Counter(row["customer_id"] for row in rows)
        selected = {key for key, _ in counts.most_common(top_customers)}
        rows = [row for row in rows if row["customer_id"] in selected]
    if top_sessions:
        counts = Counter((row["customer_id"], row["platform"], row["session_id"]) for row in rows)
        selected = {key for key, _ in counts.most_common(top_sessions)}
        rows = [
            row
            for row in rows
            if (row["customer_id"], row["platform"], row["session_id"]) in selected
        ]

    rows.sort(
        key=lambda row: (
            row["customer_id"],
            row["platform"],
            row["session_id"],
            int(float(row["session_journey_index"])) if row["session_journey_index"] else 0,
        )
    )
    return rows


def javascript_data(rows: list[dict[str, str]]) -> str:
    # Keep the browser payload focused on the detail needed by the charts/table.
    fields = [
        "customer_id",
        "platform",
        "session_id",
        "session_journey_index",
        "journey_id",
        "start_ts",
        "end_ts",
        "start_ts_value",
        "end_ts_value",
        "cluster",
        "cluster_id",
        "cluster_name",
        "cluster_name_en",
        "business_family",
        "business_family_code",
        "business_submodule",
        "business_detail",
        "sequence",
        "n_events_final",
        "severe_anomaly",
        "friction_flags",
        "next_action",
    ]
    payload = [{field: row.get(field, "") for field in fields} for row in rows]
    # Prevent a sequence value from terminating the script tag in the generated HTML.
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")


def build_html(rows: list[dict[str, str]], initial_level: str, title: str) -> str:
    data = javascript_data(rows)
    initial_level_json = json.dumps(initial_level)
    title_json = json.dumps(title, ensure_ascii=False)
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(title)}</title>
  <script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>
  <style>
    :root {{ color-scheme: light; font-family: Inter, ui-sans-serif, system-ui, sans-serif; }}
    body {{ margin: 0; background: #f4f6fa; color: #182230; }}
    main {{ max-width: 1500px; margin: 0 auto; padding: 22px 28px 48px; }}
    h1 {{ margin: 0 0 6px; font-size: 25px; }}
    .note {{ color: #586579; margin: 0 0 18px; max-width: 1050px; line-height: 1.45; }}
    .controls {{ display: flex; flex-wrap: wrap; gap: 12px; padding: 14px; background: white; border: 1px solid #dde3ec; border-radius: 10px; }}
    label {{ display: flex; flex-direction: column; gap: 5px; color: #586579; font-size: 12px; font-weight: 650; }}
    select {{ min-width: 230px; padding: 8px 10px; border: 1px solid #cbd5e1; border-radius: 7px; background: white; color: #182230; }}
    #session-select {{ min-width: 330px; }}
    .status {{ margin: 14px 0 8px; color: #334155; font-size: 14px; }}
    .chart {{ min-height: 410px; margin-top: 12px; background: white; border: 1px solid #dde3ec; border-radius: 10px; }}
    .table-wrap {{ margin-top: 12px; overflow: auto; max-height: 460px; background: white; border: 1px solid #dde3ec; border-radius: 10px; }}
    .stats {{ padding: 14px; line-height: 1.5; }}
    .stats p {{ margin: 0 0 10px; color: #475569; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 12px; }}
    th, td {{ padding: 8px 10px; border-bottom: 1px solid #edf0f4; text-align: left; vertical-align: top; white-space: nowrap; }}
    th {{ position: sticky; top: 0; z-index: 1; background: #f8fafc; color: #475569; }}
    td.sequence {{ max-width: 620px; white-space: normal; word-break: break-word; color: #475569; }}
    details {{ margin-top: 4px; }}
    summary {{ cursor: pointer; color: #2C6BB3; }}
    .empty {{ padding: 40px; color: #64748b; }}
  </style>
</head>
<body>
<main>
  <h1 id="page-title"></h1>
  <p class="note">Journey-level path ordered by <code>start_ts</code>. The source has no timestamp for each token inside a journey, so token sequences are displayed as context only; they are not assigned artificial event times. When a focus value is selected, the focus Sankey and statistics use all sessions included in this detail file.</p>
  <div class="controls">
    <label>customer_id<select id="customer-select"></select></label>
    <label>session_id<select id="session-select"></select></label>
    <label>path level<select id="level-select">
      <option value="business_family">business_family</option>
      <option value="business_submodule">business_submodule</option>
      <option value="business_detail">business_detail / action</option>
      <option value="cluster">cluster</option>
      <option value="business_family_code">business_family_code</option>
    </select></label>
    <label>focus value<select id="focus-select"></select></label>
  </div>
  <div class="status" id="status"></div>
  <div id="timeline" class="chart"></div>
  <div id="sankey" class="chart"></div>
  <div id="focus-stats" class="table-wrap"></div>
  <div id="detail-table" class="table-wrap"></div>
</main>
<script>
const DATA = {data};
const INITIAL_LEVEL = {initial_level_json};
const PAGE_TITLE = {title_json};
const LEVEL_FIELD = {{
  business_family: "business_family",
  business_submodule: "business_submodule",
  business_detail: "business_detail",
  cluster: "cluster_name",
  business_family_code: "business_family_code"
}};
const COLORS = ["#2C6BB3", "#E07A5F", "#3A9D7C", "#8E6BBE", "#D6A84F", "#4C9FCE", "#C45A9A", "#68788D", "#7A9E3A", "#D05A45"];
const customerSelect = document.getElementById("customer-select");
const sessionSelect = document.getElementById("session-select");
const levelSelect = document.getElementById("level-select");
const focusSelect = document.getElementById("focus-select");
const status = document.getElementById("status");

document.getElementById("page-title").textContent = PAGE_TITLE;
levelSelect.value = INITIAL_LEVEL;

function addOption(select, value, text) {{
  const option = document.createElement("option");
  option.value = value;
  option.textContent = text;
  select.appendChild(option);
}}

function sessionKey(row) {{ return row.customer_id + "\\u001f" + row.platform + "\\u001f" + row.session_id; }}
function customerKeys() {{
  return [...new Set(DATA.map(row => row.customer_id))].sort((a, b) => a.localeCompare(b));
}}
function sessionRowsForCustomer(customer) {{
  const seen = new Map();
  DATA.filter(row => row.customer_id === customer).forEach(row => {{
    const key = sessionKey(row);
    if (!seen.has(key)) seen.set(key, row);
  }});
  return [...seen.entries()].sort((a, b) => (a[1].start_ts_value || a[1].start_ts).localeCompare(b[1].start_ts_value || b[1].start_ts));
}}
function populateCustomers() {{
  customerSelect.innerHTML = "";
  const counts = new Map();
  DATA.forEach(row => counts.set(row.customer_id, (counts.get(row.customer_id) || 0) + 1));
  customerKeys().forEach(customer => addOption(customerSelect, customer, customer + " (" + counts.get(customer) + " journeys)"));
}}
function populateSessions() {{
  sessionSelect.innerHTML = "";
  const sessions = sessionRowsForCustomer(customerSelect.value);
  sessions.forEach(([key, first]) => {{
    const n = DATA.filter(row => sessionKey(row) === key).length;
    addOption(sessionSelect, key, first.platform + " / " + first.session_id + " (" + n + " journeys)");
  }});
}}
function populateFocusValues() {{
  const previous = focusSelect.value;
  focusSelect.innerHTML = "";
  addOption(focusSelect, "__all__", "All values");
  const counts = new Map();
  DATA.forEach(row => {{ const value = labelFor(row); counts.set(value, (counts.get(value) || 0) + 1); }});
  const values = [...counts.keys()].sort((a, b) => a.localeCompare(b));
  values.forEach(value => addOption(focusSelect, value, value + " (" + counts.get(value) + " journeys)"));
  focusSelect.value = values.includes(previous) ? previous : "__all__";
}}
function selectedRows() {{
  const key = sessionSelect.value;
  return DATA.filter(row => sessionKey(row) === key)
    .sort((a, b) => Number(a.session_journey_index) - Number(b.session_journey_index));
}}
function labelFor(row) {{
  const field = LEVEL_FIELD[levelSelect.value];
  return (row[field] || "__unknown__").trim() || "__unknown__";
}}
function colorMap(values) {{
  const map = new Map();
  values.forEach(value => {{ if (!map.has(value)) map.set(value, COLORS[map.size % COLORS.length]); }});
  return map;
}}
function allSessionRows() {{
  const groups = new Map();
  DATA.forEach(row => {{
    const key = sessionKey(row);
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key).push(row);
  }});
  groups.forEach(rows => rows.sort((a, b) => Number(a.session_journey_index) - Number(b.session_journey_index)));
  return [...groups.values()];
}}
function focusOccurrences() {{
  const focus = focusSelect.value;
  if (focus === "__all__") return [];
  const occurrences = [];
  allSessionRows().forEach(rows => rows.forEach((row, index) => {{
    if (labelFor(row) === focus) occurrences.push({{
      focus: row,
      previous: index > 0 ? rows[index - 1] : null,
      next: index + 1 < rows.length ? rows[index + 1] : null
    }});
  }}));
  return occurrences;
}}
function escapeHtml(value) {{
  return String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;").replace(/'/g, "&#039;");
}}
function renderTimeline(rows) {{
  const timeline = document.getElementById("timeline");
  if (!rows.length) {{ timeline.innerHTML = '<div class="empty">No journey rows for this selection.</div>'; return; }}
  if (typeof Plotly === "undefined") {{ timeline.innerHTML = '<div class="empty">Plotly could not be loaded. The tables below are still available; open the HTML with network access to enable charts.</div>'; return; }}
  const labels = rows.map(labelFor);
  const colors = colorMap(labels);
  const focus = focusSelect.value;
  const x = rows.map(row => row.start_ts_value || row.start_ts || row.session_journey_index);
  const y = rows.map(row => Number(row.session_journey_index));
  const trace = {{
    x, y, type: "scatter", mode: "lines+markers+text", text: labels,
    textposition: "top center", cliponaxis: false,
    line: {{ color: "#9aa9ba", width: 2 }},
    marker: {{ size: 12, color: labels.map(value => focus !== "__all__" && value === focus ? "#E63946" : colors.get(value)), line: {{ color: "white", width: 1 }} }},
    customdata: rows.map(row => [row.journey_id, row.business_family, row.business_submodule, row.cluster_name]),
    hovertemplate: "step %{{y}}<br>%{{x}}<br>journey_id=%{{customdata[0]}}<br>family=%{{customdata[1]}}<br>submodule=%{{customdata[2]}}<br>cluster=%{{customdata[3]}}<extra></extra>"
  }};
  Plotly.react(timeline, [trace], {{
    title: "Chronological journey path — " + levelSelect.value,
    xaxis: {{ title: "journey start timestamp", type: "date" }},
    yaxis: {{ title: "journey order", dtick: 1 }},
    margin: {{ l: 60, r: 30, t: 65, b: 90 }},
    hovermode: "closest", showlegend: false, plot_bgcolor: "white", paper_bgcolor: "white"
  }}, {{ responsive: true, displaylogo: false }});
}}
function renderSankey(rows) {{
  const sankey = document.getElementById("sankey");
  const pairs = [];
  if (focusSelect.value === "__all__") {{
    for (let i = 0; i < rows.length - 1; i++) pairs.push([rows[i], rows[i + 1]]);
  }} else {{
    focusOccurrences().forEach(item => {{
      if (item.previous) pairs.push([item.previous, item.focus]);
      if (item.next) pairs.push([item.focus, item.next]);
    }});
  }}
  if (!pairs.length) {{
    sankey.innerHTML = focusSelect.value === "__all__"
      ? '<div class="empty">At least two journeys are needed for a previous → next transition.</div>'
      : '<div class="empty">The focus value exists without an adjacent journey in the loaded detail set.</div>';
    return;
  }}
  if (typeof Plotly === "undefined") {{ sankey.innerHTML = '<div class="empty">Plotly could not be loaded. The focus statistics below are still available.</div>'; return; }}
  const pairCounts = new Map();
  pairs.forEach(([fromRow, toRow]) => {{
    const pair = labelFor(fromRow) + "\\u001f" + labelFor(toRow);
    pairCounts.set(pair, (pairCounts.get(pair) || 0) + 1);
  }});
  const labels = [...new Set([...pairCounts.keys()].flatMap(pair => pair.split("\\u001f")))];
  const index = new Map(labels.map((value, i) => [value, i]));
  const links = [...pairCounts.entries()].map(([pair, value]) => {{
    const [from, to] = pair.split("\\u001f");
    return {{ source: index.get(from), target: index.get(to), value }};
  }});
  Plotly.react(sankey, [{{ type: "sankey", orientation: "h", node: {{ pad: 18, thickness: 18, line: {{ color: "#64748b", width: 0.5 }}, label: labels }}, link: {{ source: links.map(x => x.source), target: links.map(x => x.target), value: links.map(x => x.value) }} }}], {{
    title: focusSelect.value === "__all__" ? "Previous → next transitions in selected session" : "Journeys immediately before/after " + focusSelect.value,
    margin: {{ l: 20, r: 20, t: 65, b: 25 }}, paper_bgcolor: "white"
  }}, {{ responsive: true, displaylogo: false }});
}}
function renderFocusStats() {{
  const target = document.getElementById("focus-stats");
  if (focusSelect.value === "__all__") {{ target.innerHTML = ''; return; }}
  const occurrences = focusOccurrences();
  if (!occurrences.length) {{
    target.innerHTML = '<div class="empty">No occurrence of this focus value exists in the loaded detail set. Rebuild with a larger --top-sessions value, or use --top-sessions 0 for all sessions.</div>';
    return;
  }}
  const sessionCount = new Set(occurrences.map(item => sessionKey(item.focus))).size;
  const customerCount = new Set(occurrences.map(item => item.focus.customer_id)).size;
  const previousCount = occurrences.filter(item => item.previous).length;
  const nextCount = occurrences.filter(item => item.next).length;
  const cell = row => row
    ? escapeHtml(labelFor(row)) + "<br><small>" + escapeHtml(row.journey_id) + "<br>" + escapeHtml(row.start_ts_value || row.start_ts) + "</small><details><summary>token sequence</summary><div class='sequence'>" + escapeHtml(row.sequence) + "</div></details>"
    : "—";
  const body = occurrences.slice(0, 250).map(item => `<tr>
    <td>${{escapeHtml(item.focus.customer_id)}}</td><td>${{escapeHtml(item.focus.platform)}}</td><td>${{escapeHtml(item.focus.session_id)}}</td>
    <td>${{cell(item.previous)}}</td><td>${{cell(item.focus)}}</td><td>${{cell(item.next)}}</td>
  </tr>`).join("");
  const suffix = occurrences.length > 250 ? " Showing the first 250 occurrences." : "";
  target.innerHTML = `<div class="stats"><p><b>Focus statistics for ${{escapeHtml(focusSelect.value)}}</b>: ${{occurrences.length}} occurrences in ${{sessionCount}} sessions and ${{customerCount}} customers. Previous available: ${{previousCount}}; next available: ${{nextCount}}.${{suffix}}</p>
    <table><thead><tr><th>customer_id</th><th>platform</th><th>session_id</th><th>previous journey</th><th>focus journey</th><th>next journey</th></tr></thead><tbody>${{body}}</tbody></table></div>`;
}}
function renderTable(rows) {{
  const target = document.getElementById("detail-table");
  if (!rows.length) {{ target.innerHTML = ''; return; }}
  const body = rows.map(row => `<tr>
    <td>${{escapeHtml(row.session_journey_index)}}</td><td>${{escapeHtml(row.start_ts_value || row.start_ts)}}</td>
    <td>${{escapeHtml(labelFor(row))}}</td><td>${{escapeHtml(row.journey_id)}}</td>
    <td>${{escapeHtml(row.business_family)}}</td><td>${{escapeHtml(row.business_submodule)}}</td>
    <td>${{escapeHtml(row.cluster_name)}}</td><td class="sequence">${{escapeHtml(row.sequence)}}</td>
  </tr>`).join("");
  target.innerHTML = `<table><thead><tr><th>step</th><th>start_ts</th><th>selected level</th><th>journey_id</th><th>business_family</th><th>business_submodule</th><th>cluster</th><th>token sequence context</th></tr></thead><tbody>${{body}}</tbody></table>`;
}}
function render() {{
  const rows = selectedRows();
  if (!rows.length) {{ status.textContent = "No rows selected."; return; }}
  const first = rows[0].start_ts_value || rows[0].start_ts;
  const last = rows[rows.length - 1].end_ts_value || rows[rows.length - 1].end_ts;
  const focusText = focusSelect.value === "__all__" ? "all values" : "focus=" + focusSelect.value;
  status.textContent = rows[0].customer_id + " · " + rows[0].platform + " · session " + rows[0].session_id + " · " + rows.length + " journeys · " + focusText + " · " + first + " → " + last;
  renderTimeline(rows); renderSankey(rows); renderFocusStats(); renderTable(rows);
}}
customerSelect.addEventListener("change", () => {{ populateSessions(); render(); }});
sessionSelect.addEventListener("change", render);
levelSelect.addEventListener("change", () => {{ populateFocusValues(); render(); }});
focusSelect.addEventListener("change", render);
populateCustomers();
populateFocusValues();
if (customerSelect.options.length) {{ customerSelect.selectedIndex = 0; populateSessions(); }}
if (sessionSelect.options.length) sessionSelect.selectedIndex = 0;
render();
</script>
</body>
</html>
"""


def main() -> None:
    args = parse_args()
    rows = read_detail(args.input, args.top_customers, args.top_sessions)
    if not rows:
        raise SystemExit("No journey rows available after filtering.")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(build_html(rows, args.level, args.title), encoding="utf-8")
    print(f"Wrote {len(rows):,} journey rows to {args.output.resolve()}")


if __name__ == "__main__":
    main()
